### PR TITLE
Add navigation list typography on doc site

### PR DESCRIPTION
**Pull request by abhisheksahani-nova**
Added navigation, list and typography on doc site

### CODE REVIEW

**Comment by ArjunJunna** [comment]
Link for typography component is missing in side bar

**Review by ArjunJunna — APPROVED** [review]
just add the link to the typography file in the sidebar of all pages. Rest everything is good.

**Comment by abhisheksahani-nova** [comment]
> just add the link to the typography file in the sidebar of all pages. Rest everything is good.

Its actually there, if yu see latest commits or in file changed

**Review by muskan-gupta-0803 — APPROVED** [review]
Looks good to merge, nicely done code and Ui.

**Pull request merged**
